name: Build Angular project
on:
  push:
    branches: 
    - Puja
jobs:
  build:
    name: Build  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Go to Folder
      run: cd suraj-demo1
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build:ci
    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
       name: deploy_dist
       path: dist

